apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: ["extensions", "apps", "configmaps", "services", "endpoints", "pods"]
  resources: ["deployments", "ingresses", "routes"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
